// Comprehensive SQL Learning Content Database
const topicsContent = {
  "CORE FOUNDATIONS": {
    "SQL Introduction": {
      explanation: "SQL (Structured Query Language) ایک زبان ہے جو ڈیٹابیس سے ڈیٹا نکالنے کے لیے استعمال ہوتی ہے۔ یہ ایک طاقتور ٹول ہے جو ڈیٹا کو تنظیم کرنے، تبدیل کرنے اور تجزیہ کرنے میں مدد دیتا ہے۔ SQL بالکل Excel جیسا ہے لیکن بہت زیادہ طاقتور ہے۔",
      syntax: "SQL کے بنیادی حکمات: SELECT, INSERT, UPDATE, DELETE, CREATE",
      beginnerExample: "SELECT * FROM students; -- تمام طالب علم کی معلومات دکھائیں",
      intermediateExample: "SELECT name, age FROM students WHERE age > 18 ORDER BY name;",
      advancedExample: "SELECT department, COUNT(*) as total_students, AVG(age) as avg_age FROM students GROUP BY department HAVING COUNT(*) > 5;",
      businessUseCase: "ایک کمپنی اپنے تمام کسٹمرز کی فہرست دیکھنا چاہتی ہے جو پچھلے 30 دن میں خریداری کریں۔",
      commonMistakes: "1. SELECT * استعمال کرنا بجائے ضروری columns کے 2. WHERE clause بھول جانا",
      interviewQuestions: "Q1: SQL کیا ہے؟ Q2: SQL اور NoSQL میں کیا فرق ہے؟",
      exercises: "1. ایک ٹیبل سے تمام ریکارڈز نکالیں 2. صرف مخصوص columns دکھائیں",
      outputExample: "| student_id | name | age |\n|---|---|---|\n| 1 | احمد | 20 |\n| 2 | علی | 22 |"
    },
    "Database Basics": {
      explanation: "ڈیٹابیس ڈیٹا کو منظم طریقے سے ذخیرہ کرنے کی جگہ ہے۔ ٹیبل میں rows اور columns ہوتے ہیں۔ ہر column کا ایک نام اور type ہوتا ہے۔",
      syntax: "CREATE DATABASE database_name; CREATE TABLE table_name (column_name datatype);",
      beginnerExample: "CREATE TABLE employees (id INT, name VARCHAR(100), salary DECIMAL(10,2));",
      intermediateExample: "CREATE TABLE orders (order_id INT PRIMARY KEY, customer_id INT, order_date DATE, amount DECIMAL(10,2));",
      advancedExample: "CREATE TABLE transactions (transaction_id INT PRIMARY KEY AUTO_INCREMENT, customer_id INT FOREIGN KEY REFERENCES customers(id), amount DECIMAL(15,2), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);",
      businessUseCase: "ای کامرس کمپنی کو اپنے تمام آرڈرز، کسٹمرز اور پروڈکٹس کو ٹیبلز میں منظم کرنا ہے۔",
      commonMistakes: "1. غلط datatype استعمال کرنا 2. Primary Key نہ دینا",
      interviewQuestions: "Q1: ٹیبل کیا ہے؟ Q2: Primary Key کیا ہے؟",
      exercises: "1. ایک customers ٹیبل بنائیں 2. مختلف columns کے لیے صحیح datatypes منتخب کریں",
      outputExample: "Table created successfully"
    },
    "DDL vs DML vs DQL": {
      explanation: "DDL (Data Definition Language) - ڈیٹابیس کی ساخت بناتا ہے۔ DML (Data Manipulation Language) - ڈیٹا میں تبدیلی کرتا ہے۔ DQL (Data Query Language) - ڈیٹا نکالتا ہے۔",
      syntax: "DDL: CREATE, ALTER, DROP | DML: INSERT, UPDATE, DELETE | DQL: SELECT",
      beginnerExample: "DDL: CREATE TABLE | DML: INSERT INTO | DQL: SELECT FROM",
      intermediateExample: "DDL: ALTER TABLE employees ADD COLUMN department VARCHAR(50); | DML: UPDATE employees SET salary = 50000 WHERE id = 1;",
      advancedExample: "DDL: ALTER TABLE employees MODIFY COLUMN salary DECIMAL(12,2); | DML: DELETE FROM employees WHERE hire_date < '2020-01-01';",
      businessUseCase: "ڈیٹابیس میں نیا کالم شامل کرنا اور پرانے ڈیٹا کو صاف کرنا۔",
      commonMistakes: "1. DDL اور DML کو الجھانا 2. COMMIT بھول جانا",
      interviewQuestions: "Q1: DDL اور DML میں کیا فرق ہے؟ Q2: DROP اور DELETE میں کیا فرق ہے؟",
      exercises: "1. ایک ٹیبل بنائیں (DDL) 2. ڈیٹا شامل کریں (DML) 3. ڈیٹا نکالیں (DQL)",
      outputExample: "Query executed successfully"
    },
    "SELECT": {
      explanation: "SELECT حکم ڈیٹابیس سے ڈیٹا نکالنے کے لیے استعمال ہوتا ہے۔ یہ SQL کا سب سے اہم حکم ہے۔",
      syntax: "SELECT column1, column2 FROM table_name;",
      beginnerExample: "SELECT name, email FROM customers;",
      intermediateExample: "SELECT DISTINCT city FROM customers ORDER BY city;",
      advancedExample: "SELECT customer_id, COUNT(*) as order_count, SUM(amount) as total_spent FROM orders GROUP BY customer_id HAVING COUNT(*) > 5;",
      businessUseCase: "سب سے زیادہ خریداری کرنے والے کسٹمرز کو دیکھنا۔",
      commonMistakes: "1. غلط column کا نام 2. ٹیبل کا نام غلط لکھنا",
      interviewQuestions: "Q1: SELECT * اور SELECT column_name میں کیا فرق ہے؟",
      exercises: "1. تمام columns نکالیں 2. مخصوص columns نکالیں 3. DISTINCT استعمال کریں",
      outputExample: "| name | email |\n|---|---|\n| احمد | ahmad@email.com |"
    },
    "FROM": {
      explanation: "FROM clause بتاتا ہے کہ ڈیٹا کس ٹیبل سے نکالنا ہے۔ ہر SELECT statement میں FROM ضروری ہے۔",
      syntax: "SELECT columns FROM table_name;",
      beginnerExample: "SELECT * FROM products;",
      intermediateExample: "SELECT * FROM orders FROM 2024;",
      advancedExample: "SELECT o.order_id, c.customer_name FROM orders o JOIN customers c ON o.customer_id = c.id;",
      businessUseCase: "کسی مخصوص ٹیبل سے ڈیٹا نکالنا۔",
      commonMistakes: "1. FROM بھول جانا 2. ٹیبل کا نام غلط لکھنا",
      interviewQuestions: "Q1: FROM clause کا کیا مقصد ہے؟",
      exercises: "1. مختلف ٹیبلز سے ڈیٹا نکالیں",
      outputExample: "Data retrieved from table"
    },
    "WHERE": {
      explanation: "WHERE clause ڈیٹا کو فلٹر کرنے کے لیے استعمال ہوتا ہے۔ یہ شرط لگاتا ہے کہ کون سے rows نکالنے ہیں۔",
      syntax: "SELECT columns FROM table_name WHERE condition;",
      beginnerExample: "SELECT * FROM employees WHERE salary > 50000;",
      intermediateExample: "SELECT name, age FROM students WHERE age > 18 AND city = 'Karachi';",
      advancedExample: "SELECT * FROM orders WHERE order_date BETWEEN '2024-01-01' AND '2024-12-31' AND status = 'completed';",
      businessUseCase: "صرف وہ آرڈرز دیکھنا جو مکمل ہو چکے ہوں۔",
      commonMistakes: "1. غلط operator استعمال کرنا 2. quotes بھول جانا",
      interviewQuestions: "Q1: WHERE اور HAVING میں کیا فرق ہے؟",
      exercises: "1. مختلف conditions استعمال کریں 2. AND/OR operators استعمال کریں",
      outputExample: "| name | salary |\n|---|---|\n| علی | 60000 |"
    },
    "DISTINCT": {
      explanation: "DISTINCT صرف منفرد values دکھاتا ہے۔ اگر کوئی value دوبارہ آئے تو وہ صرف ایک بار دکھائی دیتا ہے۔",
      syntax: "SELECT DISTINCT column FROM table_name;",
      beginnerExample: "SELECT DISTINCT city FROM customers;",
      intermediateExample: "SELECT DISTINCT department, job_title FROM employees;",
      advancedExample: "SELECT DISTINCT customer_id FROM orders WHERE order_date > '2024-01-01';",
      businessUseCase: "کتنے منفرد شہروں میں کسٹمرز ہیں یہ جاننا۔",
      commonMistakes: "1. DISTINCT کے بغیر duplicate values آتے ہیں",
      interviewQuestions: "Q1: DISTINCT کا کیا فائدہ ہے؟",
      exercises: "1. منفرد values نکالیں",
      outputExample: "| city |\n|---|\n| Karachi |\n| Lahore |\n| Islamabad |"
    },
    "ORDER BY": {
      explanation: "ORDER BY نتائج کو ترتیب دیتا ہے۔ ASC (بڑھتی ہوئی) یا DESC (گھٹتی ہوئی) ترتیب میں۔",
      syntax: "SELECT columns FROM table_name ORDER BY column ASC/DESC;",
      beginnerExample: "SELECT * FROM employees ORDER BY salary DESC;",
      intermediateExample: "SELECT name, age FROM students ORDER BY age ASC, name ASC;",
      advancedExample: "SELECT customer_id, SUM(amount) as total FROM orders GROUP BY customer_id ORDER BY total DESC LIMIT 10;",
      businessUseCase: "سب سے زیادہ خریداری کرنے والے کسٹمرز کو ترتیب سے دیکھنا۔",
      commonMistakes: "1. ASC/DESC بھول جانا 2. غلط column کو order کرنا",
      interviewQuestions: "Q1: ORDER BY کے بغیر کیا ہوتا ہے؟",
      exercises: "1. مختلف ترتیبوں میں ڈیٹا دیکھیں",
      outputExample: "| name | salary |\n|---|---|\n| احمد | 80000 |\n| علی | 60000 |"
    },
    "GROUP BY": {
      explanation: "GROUP BY ڈیٹا کو گروپس میں تقسیم کرتا ہے۔ عام طور پر aggregate functions کے ساتھ استعمال ہوتا ہے۔",
      syntax: "SELECT column, COUNT(*) FROM table_name GROUP BY column;",
      beginnerExample: "SELECT department, COUNT(*) FROM employees GROUP BY department;",
      intermediateExample: "SELECT city, AVG(age) FROM customers GROUP BY city;",
      advancedExample: "SELECT department, job_title, COUNT(*) as count, AVG(salary) as avg_salary FROM employees GROUP BY department, job_title;",
      businessUseCase: "ہر شہر میں کتنے کسٹمرز ہیں یہ جاننا۔",
      commonMistakes: "1. GROUP BY کے بغیر aggregate function 2. SELECT میں غیر grouped column",
      interviewQuestions: "Q1: GROUP BY کا کیا مقصد ہے؟",
      exercises: "1. مختلف columns کے لحاظ سے گروپ بنائیں",
      outputExample: "| department | count |\n|---|---|\n| Sales | 15 |\n| IT | 20 |"
    },
    "HAVING": {
      explanation: "HAVING GROUP BY کے بعد شرط لگاتا ہے۔ WHERE سے فرق یہ ہے کہ HAVING aggregate functions کے ساتھ کام کرتا ہے۔",
      syntax: "SELECT column, COUNT(*) FROM table_name GROUP BY column HAVING COUNT(*) > 5;",
      beginnerExample: "SELECT department, COUNT(*) FROM employees GROUP BY department HAVING COUNT(*) > 3;",
      intermediateExample: "SELECT city, AVG(salary) FROM employees GROUP BY city HAVING AVG(salary) > 50000;",
      advancedExample: "SELECT customer_id, COUNT(*) as order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 10 AND SUM(amount) > 100000;",
      businessUseCase: "صرف وہ شہر دیکھنا جہاں 5 سے زیادہ کسٹمرز ہوں۔",
      commonMistakes: "1. WHERE کی جگہ HAVING استعمال کرنا 2. HAVING بغیر GROUP BY",
      interviewQuestions: "Q1: WHERE اور HAVING میں کیا فرق ہے؟",
      exercises: "1. مختلف conditions کے ساتھ HAVING استعمال کریں",
      outputExample: "| city | customer_count |\n|---|---|\n| Karachi | 25 |"
    },
    "LIMIT / TOP": {
      explanation: "LIMIT یا TOP نتائج کی تعداد محدود کرتا ہے۔ مثال کے طور پر صرف پہلے 10 rows دکھانا۔",
      syntax: "SELECT * FROM table_name LIMIT 10; -- MySQL/PostgreSQL\nSELECT TOP 10 * FROM table_name; -- SQL Server",
      beginnerExample: "SELECT * FROM employees LIMIT 5;",
      intermediateExample: "SELECT * FROM orders ORDER BY order_date DESC LIMIT 10;",
      advancedExample: "SELECT customer_id, SUM(amount) as total FROM orders GROUP BY customer_id ORDER BY total DESC LIMIT 5;",
      businessUseCase: "سب سے بہترین 10 فروخت والے صلیح کو دیکھنا۔",
      commonMistakes: "1. LIMIT بغیر ORDER BY 2. LIMIT کو غلط جگہ لگانا",
      interviewQuestions: "Q1: LIMIT کا کیا فائدہ ہے؟",
      exercises: "1. مختلف تعداد میں rows نکالیں",
      outputExample: "First 5 records displayed"
    },
    "AND / OR / NOT": {
      explanation: "یہ logical operators ہیں جو شرائط کو ملاتے ہیں۔ AND دونوں شرائط پوری کرتا ہے۔ OR میں سے کوئی ایک۔ NOT منفی کرتا ہے۔",
      syntax: "SELECT * FROM table WHERE condition1 AND condition2; SELECT * FROM table WHERE condition1 OR condition2; SELECT * FROM table WHERE NOT condition;",
      beginnerExample: "SELECT * FROM employees WHERE age > 25 AND salary > 50000;",
      intermediateExample: "SELECT * FROM customers WHERE city = 'Karachi' OR city = 'Lahore';",
      advancedExample: "SELECT * FROM orders WHERE (status = 'completed' AND amount > 10000) OR (status = 'pending' AND created_at > '2024-01-01');",
      businessUseCase: "وہ کسٹمرز دیکھنا جو Karachi یا Lahore میں ہوں اور 5 سے زیادہ خریداری کی ہو۔",
      commonMistakes: "1. Parentheses بھول جانا 2. غلط operator استعمال کرنا",
      interviewQuestions: "Q1: AND اور OR میں کیا فرق ہے؟",
      exercises: "1. مختلف combinations استعمال کریں",
      outputExample: "| name | city | purchases |\n|---|---|---|\n| احمد | Karachi | 8 |"
    },
    "IN": {
      explanation: "IN operator کسی column میں متعدد values تلاش کرتا ہے۔ یہ OR کا مختصر طریقہ ہے۔",
      syntax: "SELECT * FROM table WHERE column IN (value1, value2, value3);",
      beginnerExample: "SELECT * FROM employees WHERE department IN ('Sales', 'Marketing', 'IT');",
      intermediateExample: "SELECT * FROM orders WHERE status IN ('completed', 'shipped', 'delivered');",
      advancedExample: "SELECT * FROM customers WHERE customer_id IN (SELECT customer_id FROM orders WHERE amount > 50000);",
      businessUseCase: "صرف مخصوص departments کے employees دیکھنا۔",
      commonMistakes: "1. Quotes بھول جانا 2. IN بغیر parentheses",
      interviewQuestions: "Q1: IN اور OR میں کیا فرق ہے؟",
      exercises: "1. متعدد values کے ساتھ IN استعمال کریں",
      outputExample: "| name | department |\n|---|---|\n| احمد | Sales |"
    },
    "BETWEEN": {
      explanation: "BETWEEN ایک range میں values تلاش کرتا ہے۔ یہ >= اور <= کا مختصر طریقہ ہے۔",
      syntax: "SELECT * FROM table WHERE column BETWEEN value1 AND value2;",
      beginnerExample: "SELECT * FROM employees WHERE salary BETWEEN 40000 AND 80000;",
      intermediateExample: "SELECT * FROM orders WHERE order_date BETWEEN '2024-01-01' AND '2024-12-31';",
      advancedExample: "SELECT * FROM transactions WHERE amount BETWEEN 1000 AND 100000 AND transaction_date BETWEEN '2024-01-01' AND '2024-06-30';",
      businessUseCase: "ایک مخصوص تاریخ کے دوران کے آرڈرز دیکھنا۔",
      commonMistakes: "1. AND بھول جانا 2. غلط order میں values دینا",
      interviewQuestions: "Q1: BETWEEN کا کیا فائدہ ہے؟",
      exercises: "1. مختلف ranges استعمال کریں",
      outputExample: "| name | salary |\n|---|---|\n| علی | 60000 |"
    },
    "LIKE": {
      explanation: "LIKE pattern matching کے لیے استعمال ہوتا ہے۔ % کسی بھی characters کو match کرتا ہے۔ _ ایک character کو۔",
      syntax: "SELECT * FROM table WHERE column LIKE 'pattern%'; -- % = کوئی بھی characters\nSELECT * FROM table WHERE column LIKE '_pattern'; -- _ = ایک character",
      beginnerExample: "SELECT * FROM customers WHERE name LIKE 'A%';",
      intermediateExample: "SELECT * FROM employees WHERE email LIKE '%@gmail.com';",
      advancedExample: "SELECT * FROM products WHERE product_name LIKE '%laptop%' AND category LIKE 'Electronics%';",
      businessUseCase: "وہ کسٹمرز ڈھونڈنا جن کے نام 'A' سے شروع ہوں۔",
      commonMistakes: "1. % اور _ کو الجھانا 2. Case sensitivity",
      interviewQuestions: "Q1: LIKE میں % اور _ میں کیا فرق ہے؟",
      exercises: "1. مختلف patterns استعمال کریں",
      outputExample: "| name |\n|---|\n| احمد |\n| علی |"
    },
    "IS NULL": {
      explanation: "IS NULL خالی values تلاش کرتا ہے۔ NULL کا مطلب ہے کہ کوئی value نہیں ہے۔",
      syntax: "SELECT * FROM table WHERE column IS NULL; SELECT * FROM table WHERE column IS NOT NULL;",
      beginnerExample: "SELECT * FROM employees WHERE phone_number IS NULL;",
      intermediateExample: "SELECT * FROM orders WHERE delivery_date IS NULL;",
      advancedExample: "SELECT * FROM customers WHERE phone IS NULL OR email IS NULL;",
      businessUseCase: "وہ کسٹمرز دیکھنا جن کے پاس phone number نہیں ہے۔",
      commonMistakes: "1. = NULL استعمال کرنا بجائے IS NULL 2. NULL کو string سمجھنا",
      interviewQuestions: "Q1: = NULL اور IS NULL میں کیا فرق ہے؟",
      exercises: "1. NULL values تلاش کریں",
      outputExample: "| name | phone |\n|---|---|\n| احمد | NULL |"
    },
    "COALESCE": {
      explanation: "COALESCE پہلی non-NULL value واپس کرتا ہے۔ یہ NULL values کو handle کرنے میں مدد دیتا ہے۔",
      syntax: "SELECT COALESCE(column1, column2, 'default_value') FROM table;",
      beginnerExample: "SELECT name, COALESCE(phone, 'No phone') FROM customers;",
      intermediateExample: "SELECT order_id, COALESCE(notes, 'No notes available') FROM orders;",
      advancedExample: "SELECT customer_id, COALESCE(middle_name, '') + ' ' + last_name as full_name FROM customers;",
      businessUseCase: "کسٹمرز کی معلومات دیکھتے وقت خالی جگہوں کو پر کرنا۔",
      commonMistakes: "1. COALESCE کے بغیر NULL values مسائل پیدا کرتے ہیں",
      interviewQuestions: "Q1: COALESCE کا کیا فائدہ ہے؟",
      exercises: "1. COALESCE کے ساتھ default values دیں",
      outputExample: "| name | phone |\n|---|---|\n| احمد | 03001234567 |\n| علی | No phone |"
    },
    "Aggregate Functions": {
      explanation: "Aggregate functions متعدد rows پر کام کرتے ہیں اور ایک نتیجہ دیتے ہیں۔ مثال: COUNT, SUM, AVG, MIN, MAX",
      syntax: "SELECT COUNT(*), SUM(column), AVG(column), MIN(column), MAX(column) FROM table;",
      beginnerExample: "SELECT COUNT(*) FROM employees;",
      intermediateExample: "SELECT COUNT(DISTINCT department) FROM employees;",
      advancedExample: "SELECT department, COUNT(*) as emp_count, AVG(salary) as avg_salary, MAX(salary) as max_salary FROM employees GROUP BY department;",
      businessUseCase: "کل کتنے کسٹمرز ہیں اور ان کی اوسط خریداری کتنی ہے۔",
      commonMistakes: "1. Aggregate function بغیر GROUP BY 2. NULL values کو ignore کرنا",
      interviewQuestions: "Q1: Aggregate functions کیا ہیں؟",
      exercises: "1. مختلف aggregate functions استعمال کریں",
      outputExample: "| COUNT(*) | AVG(salary) |\n|---|---|\n| 50 | 55000 |"
    },
    "COUNT": {
      explanation: "COUNT rows کی تعداد گنتا ہے۔ COUNT(*) تمام rows گنتا ہے۔ COUNT(column) صرف non-NULL values گنتا ہے۔",
      syntax: "SELECT COUNT(*) FROM table; SELECT COUNT(column) FROM table;",
      beginnerExample: "SELECT COUNT(*) FROM employees;",
      intermediateExample: "SELECT COUNT(DISTINCT department) FROM employees;",
      advancedExample: "SELECT department, COUNT(*) as emp_count FROM employees GROUP BY department HAVING COUNT(*) > 5;",
      businessUseCase: "کتنے آرڈرز ہر ماہ میں آتے ہیں۔",
      commonMistakes: "1. COUNT(*) اور COUNT(column) کو الجھانا",
      interviewQuestions: "Q1: COUNT(*) اور COUNT(column) میں کیا فرق ہے؟",
      exercises: "1. مختلف COUNT استعمال کریں",
      outputExample: "| COUNT(*) |\n|---|\n| 150 |"
    },
    "SUM": {
      explanation: "SUM ایک column کی تمام values کو جمع کرتا ہے۔ صرف numeric columns کے لیے۔",
      syntax: "SELECT SUM(column) FROM table;",
      beginnerExample: "SELECT SUM(salary) FROM employees;",
      intermediateExample: "SELECT department, SUM(salary) FROM employees GROUP BY department;",
      advancedExample: "SELECT customer_id, SUM(amount) as total_spent FROM orders WHERE order_date >= '2024-01-01' GROUP BY customer_id;",
      businessUseCase: "کل فروخت کتنی ہے۔",
      commonMistakes: "1. SUM کو text column پر استعمال کرنا",
      interviewQuestions: "Q1: SUM کا کیا کام ہے؟",
      exercises: "1. مختلف columns کو sum کریں",
      outputExample: "| SUM(salary) |\n|---|\n| 2750000 |"
    },
    "AVG": {
      explanation: "AVG ایک column کی اوسط نکالتا ہے۔ NULL values کو ignore کرتا ہے۔",
      syntax: "SELECT AVG(column) FROM table;",
      beginnerExample: "SELECT AVG(salary) FROM employees;",
      intermediateExample: "SELECT department, AVG(salary) FROM employees GROUP BY department;",
      advancedExample: "SELECT customer_id, AVG(amount) as avg_order_value FROM orders WHERE status = 'completed' GROUP BY customer_id;",
      businessUseCase: "اوسط آرڈر کی قیمت کتنی ہے۔",
      commonMistakes: "1. AVG میں NULL values کو سمجھنا",
      interviewQuestions: "Q1: AVG کیسے کام کرتا ہے؟",
      exercises: "1. اوسط نکالیں",
      outputExample: "| AVG(salary) |\n|---|\n| 55000 |"
    },
    "MIN": {
      explanation: "MIN سب سے کم value نکالتا ہے۔",
      syntax: "SELECT MIN(column) FROM table;",
      beginnerExample: "SELECT MIN(salary) FROM employees;",
      intermediateExample: "SELECT department, MIN(salary) FROM employees GROUP BY department;",
      advancedExample: "SELECT customer_id, MIN(order_date) as first_order_date FROM orders GROUP BY customer_id;",
      businessUseCase: "سب سے کم تنخواہ کتنی ہے۔",
      commonMistakes: "1. MIN کو غلط column پر استعمال کرنا",
      interviewQuestions: "Q1: MIN کا کیا مقصد ہے؟",
      exercises: "1. کم سے کم value نکالیں",
      outputExample: "| MIN(salary) |\n|---|\n| 30000 |"
    },
    "MAX": {
      explanation: "MAX سب سے زیادہ value نکالتا ہے۔",
      syntax: "SELECT MAX(column) FROM table;",
      beginnerExample: "SELECT MAX(salary) FROM employees;",
      intermediateExample: "SELECT department, MAX(salary) FROM employees GROUP BY department;",
      advancedExample: "SELECT customer_id, MAX(order_date) as last_order_date FROM orders GROUP BY customer_id;",
      businessUseCase: "سب سے زیادہ تنخواہ کتنی ہے۔",
      commonMistakes: "1. MAX کو غلط column پر استعمال کرنا",
      interviewQuestions: "Q1: MAX کا کیا مقصد ہے؟",
      exercises: "1. سب سے زیادہ value نکالیں",
      outputExample: "| MAX(salary) |\n|---|\n| 150000 |"
    }
  },
  "INTERMEDIATE QUERYING": {
    "INNER JOIN": {
      explanation: "INNER JOIN دونوں tables میں موجود matching records نکالتا ہے۔ جو records دونوں میں نہیں ہیں وہ نہیں آتے۔",
      syntax: "SELECT * FROM table1 INNER JOIN table2 ON table1.id = table2.id;",
      beginnerExample: "SELECT e.name, d.department_name FROM employees e INNER JOIN departments d ON e.department_id = d.id;",
      intermediateExample: "SELECT o.order_id, c.customer_name, p.product_name FROM orders o INNER JOIN customers c ON o.customer_id = c.id INNER JOIN products p ON o.product_id = p.id;",
      advancedExample: "SELECT o.order_id, c.customer_name, SUM(oi.quantity * oi.price) as total FROM orders o INNER JOIN customers c ON o.customer_id = c.id INNER JOIN order_items oi ON o.order_id = oi.order_id GROUP BY o.order_id, c.customer_name;",
      businessUseCase: "ہر آرڈر کے ساتھ کسٹمر کی معلومات دیکھنا۔",
      commonMistakes: "1. ON condition غلط لگانا 2. Alias استعمال نہ کرنا",
      interviewQuestions: "Q1: INNER JOIN کیا ہے؟ Q2: INNER JOIN اور LEFT JOIN میں کیا فرق ہے؟",
      exercises: "1. دو tables کو join کریں 2. متعدد joins کریں",
      outputExample: "| order_id | customer_name | product_name |\n|---|---|---|\n| 1 | احمد | Laptop |"
    },
    "LEFT JOIN": {
      explanation: "LEFT JOIN بائیں table کے تمام records نکالتا ہے، چاہے دائیں table میں match ہو یا نہ ہو۔",
      syntax: "SELECT * FROM table1 LEFT JOIN table2 ON table1.id = table2.id;",
      beginnerExample: "SELECT c.customer_name, o.order_id FROM customers c LEFT JOIN orders o ON c.id = o.customer_id;",
      intermediateExample: "SELECT e.name, d.department_name FROM employees e LEFT JOIN departments d ON e.department_id = d.id;",
      advancedExample: "SELECT c.customer_name, COUNT(o.order_id) as order_count FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.customer_name;",
      businessUseCase: "تمام کسٹمرز دیکھنا، چاہے انہوں نے آرڈر کیا ہو یا نہ ہو۔",
      commonMistakes: "1. LEFT اور RIGHT کو الجھانا 2. NULL values کو handle نہ کرنا",
      interviewQuestions: "Q1: LEFT JOIN کیا ہے؟",
      exercises: "1. LEFT JOIN استعمال کریں",
      outputExample: "| customer_name | order_id |\n|---|---|\n| احمد | 1 |\n| علی | NULL |"
    },
    "RIGHT JOIN": {
      explanation: "RIGHT JOIN دائیں table کے تمام records نکالتا ہے، چاہے بائیں table میں match ہو یا نہ ہو۔",
      syntax: "SELECT * FROM table1 RIGHT JOIN table2 ON table1.id = table2.id;",
      beginnerExample: "SELECT c.customer_name, o.order_id FROM customers c RIGHT JOIN orders o ON c.id = o.customer_id;",
      intermediateExample: "SELECT e.name, d.department_name FROM employees e RIGHT JOIN departments d ON e.department_id = d.id;",
      advancedExample: "SELECT d.department_name, COUNT(e.id) as emp_count FROM employees e RIGHT JOIN departments d ON e.department_id = d.id GROUP BY d.id, d.department_name;",
      businessUseCase: "تمام departments دیکھنا، چاہے ان میں employees ہوں یا نہ ہوں۔",
      commonMistakes: "1. RIGHT JOIN کو سمجھنا",
      interviewQuestions: "Q1: RIGHT JOIN کیا ہے؟",
      exercises: "1. RIGHT JOIN استعمال کریں",
      outputExample: "| department_name | emp_count |\n|---|---|\n| Sales | 15 |\n| HR | 0 |"
    },
    "FULL JOIN": {
      explanation: "FULL JOIN دونوں tables کے تمام records نکالتا ہے، چاہے match ہو یا نہ ہو۔",
      syntax: "SELECT * FROM table1 FULL JOIN table2 ON table1.id = table2.id;",
      beginnerExample: "SELECT c.customer_name, o.order_id FROM customers c FULL JOIN orders o ON c.id = o.customer_id;",
      intermediateExample: "SELECT e.name, d.department_name FROM employees e FULL JOIN departments d ON e.department_id = d.id;",
      advancedExample: "SELECT COALESCE(c.customer_name, 'Unknown') as customer_name, COUNT(o.order_id) as order_count FROM customers c FULL JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.customer_name;",
      businessUseCase: "تمام کسٹمرز اور تمام آرڈرز دیکھنا۔",
      commonMistakes: "1. FULL JOIN ہمیشہ دستیاب نہیں ہے",
      interviewQuestions: "Q1: FULL JOIN کیا ہے؟",
      exercises: "1. FULL JOIN استعمال کریں",
      outputExample: "| customer_name | order_id |\n|---|---|\n| احمد | 1 |\n| علی | NULL |"
    },
    "SELF JOIN": {
      explanation: "SELF JOIN ایک table کو اپنے آپ سے join کرتا ہے۔ عام طور پر hierarchical data کے لیے۔",
      syntax: "SELECT * FROM table1 t1 JOIN table1 t2 ON t1.id = t2.parent_id;",
      beginnerExample: "SELECT e1.name as employee, e2.name as manager FROM employees e1 JOIN employees e2 ON e1.manager_id = e2.id;",
      intermediateExample: "SELECT e1.name, e1.salary, e2.name as manager_name, e2.salary as manager_salary FROM employees e1 LEFT JOIN employees e2 ON e1.manager_id = e2.id;",
      advancedExample: "SELECT e1.name, e1.department_id, e2.name as colleague FROM employees e1 JOIN employees e2 ON e1.department_id = e2.department_id AND e1.id != e2.id;",
      businessUseCase: "ہر employee کا manager دیکھنا۔",
      commonMistakes: "1. Alias استعمال نہ کرنا 2. Condition غلط لگانا",
      interviewQuestions: "Q1: SELF JOIN کیا ہے؟",
      exercises: "1. SELF JOIN استعمال کریں",
      outputExample: "| employee | manager |\n|---|---|\n| احمد | علی |"
    },
    "CROSS JOIN": {
      explanation: "CROSS JOIN دونوں tables کا Cartesian product نکالتا ہے۔ ہر row پہلی table سے ہر row دوسری table سے جڑتا ہے۔",
      syntax: "SELECT * FROM table1 CROSS JOIN table2;",
      beginnerExample: "SELECT c.color, s.size FROM colors c CROSS JOIN sizes s;",
      intermediateExample: "SELECT d.day, t.time_slot FROM days d CROSS JOIN time_slots t;",
      advancedExample: "SELECT c.customer_id, p.product_id FROM customers c CROSS JOIN products p;",
      businessUseCase: "تمام ممکنہ combinations بنانا۔",
      commonMistakes: "1. CROSS JOIN بہت بڑا result set بناتا ہے",
      interviewQuestions: "Q1: CROSS JOIN کیا ہے؟",
      exercises: "1. CROSS JOIN استعمال کریں",
      outputExample: "| color | size |\n|---|---|\n| Red | S |\n| Red | M |"
    },
    "UNION": {
      explanation: "UNION دو queries کے نتائج کو ملاتا ہے۔ Duplicate rows کو ہٹاتا ہے۔",
      syntax: "SELECT column FROM table1 UNION SELECT column FROM table2;",
      beginnerExample: "SELECT name FROM employees UNION SELECT name FROM contractors;",
      intermediateExample: "SELECT customer_name FROM customers WHERE city = 'Karachi' UNION SELECT customer_name FROM customers WHERE city = 'Lahore';",
      advancedExample: "SELECT 'Employee' as type, name FROM employees UNION SELECT 'Contractor' as type, name FROM contractors;",
      businessUseCase: "employees اور contractors کی مشترکہ فہرست۔",
      commonMistakes: "1. Columns کی تعداد مختلف ہونا 2. Data types مختلف ہونا",
      interviewQuestions: "Q1: UNION کیا ہے؟",
      exercises: "1. UNION استعمال کریں",
      outputExample: "| name |\n|---|\n| احمد |\n| علی |"
    },
    "UNION ALL": {
      explanation: "UNION ALL دو queries کے نتائج کو ملاتا ہے۔ Duplicate rows کو رکھتا ہے۔",
      syntax: "SELECT column FROM table1 UNION ALL SELECT column FROM table2;",
      beginnerExample: "SELECT name FROM employees UNION ALL SELECT name FROM contractors;",
      intermediateExample: "SELECT order_id FROM orders_2023 UNION ALL SELECT order_id FROM orders_2024;",
      advancedExample: "SELECT customer_id, amount FROM sales_2023 UNION ALL SELECT customer_id, amount FROM sales_2024;",
      businessUseCase: "دونوں سالوں کے sales کو ملانا۔",
      commonMistakes: "1. UNION اور UNION ALL کو الجھانا",
      interviewQuestions: "Q1: UNION اور UNION ALL میں کیا فرق ہے؟",
      exercises: "1. UNION ALL استعمال کریں",
      outputExample: "| name |\n|---|\n| احمد |\n| علی |\n| احمد |"
    },
    "INTERSECT": {
      explanation: "INTERSECT دونوں queries میں موجود مشترک rows نکالتا ہے۔",
      syntax: "SELECT column FROM table1 INTERSECT SELECT column FROM table2;",
      beginnerExample: "SELECT customer_id FROM orders_2023 INTERSECT SELECT customer_id FROM orders_2024;",
      intermediateExample: "SELECT employee_id FROM sales_team INTERSECT SELECT employee_id FROM marketing_team;",
      advancedExample: "SELECT product_id FROM bestsellers_2023 INTERSECT SELECT product_id FROM bestsellers_2024;",
      businessUseCase: "وہ کسٹمرز جنہوں نے دونوں سالوں میں خریداری کی۔",
      commonMistakes: "1. INTERSECT ہمیشہ دستیاب نہیں ہے",
      interviewQuestions: "Q1: INTERSECT کیا ہے؟",
      exercises: "1. INTERSECT استعمال کریں",
      outputExample: "| customer_id |\n|---|\n| 1 |\n| 5 |"
    },
    "CASE WHEN": {
      explanation: "CASE WHEN if-else logic استعمال کرتا ہے۔ مختلف conditions کے لیے مختلف values دے سکتے ہیں۔",
      syntax: "SELECT CASE WHEN condition1 THEN value1 WHEN condition2 THEN value2 ELSE value3 END FROM table;",
      beginnerExample: "SELECT name, CASE WHEN age >= 18 THEN 'Adult' ELSE 'Minor' END as age_group FROM customers;",
      intermediateExample: "SELECT name, salary, CASE WHEN salary > 100000 THEN 'High' WHEN salary > 50000 THEN 'Medium' ELSE 'Low' END as salary_range FROM employees;",
      advancedExample: "SELECT customer_id, SUM(amount) as total_spent, CASE WHEN SUM(amount) > 100000 THEN 'VIP' WHEN SUM(amount) > 50000 THEN 'Premium' ELSE 'Regular' END as customer_type FROM orders GROUP BY customer_id;",
      businessUseCase: "کسٹمرز کو ان کی خریداری کی بنیاد پر categories میں تقسیم کرنا۔",
      commonMistakes: "1. ELSE بھول جانا 2. Conditions غلط ترتیب میں",
      interviewQuestions: "Q1: CASE WHEN کیا ہے؟",
      exercises: "1. مختلف conditions کے ساتھ CASE استعمال کریں",
      outputExample: "| name | age_group |\n|---|---|\n| احمد | Adult |\n| علی | Adult |"
    },
    "Date Functions": {
      explanation: "Date functions تاریخوں کے ساتھ کام کرتے ہیں۔ تاریخوں کو شامل کرنا، گھٹانا، یا موازنہ کرنا۔",
      syntax: "SELECT GETDATE(), DATEADD(day, 1, GETDATE()), DATEDIFF(day, date1, date2) FROM table;",
      beginnerExample: "SELECT order_date, GETDATE() as today FROM orders;",
      intermediateExample: "SELECT order_date, DATEADD(day, 7, order_date) as delivery_date FROM orders;",
      advancedExample: "SELECT order_id, DATEDIFF(day, order_date, delivery_date) as days_to_deliver FROM orders;",
      businessUseCase: "کتنے دن میں delivery ہوئی یہ معلوم کرنا۔",
      commonMistakes: "1. Date format غلط ہونا 2. Functions کا نام غلط ہونا",
      interviewQuestions: "Q1: Date functions کیا ہیں؟",
      exercises: "1. مختلف date functions استعمال کریں",
      outputExample: "| order_date | delivery_date |\n|---|---|\n| 2024-01-01 | 2024-01-08 |"
    },
    "DATEDIFF": {
      explanation: "DATEDIFF دو تاریخوں کے درمیان فرق نکالتا ہے۔ دن، ماہ، سال وغیرہ میں۔",
      syntax: "SELECT DATEDIFF(day, date1, date2) FROM table;",
      beginnerExample: "SELECT order_date, DATEDIFF(day, order_date, GETDATE()) as days_ago FROM orders;",
      intermediateExample: "SELECT customer_id, DATEDIFF(day, MIN(order_date), MAX(order_date)) as customer_lifetime_days FROM orders GROUP BY customer_id;",
      advancedExample: "SELECT order_id, DATEDIFF(day, order_date, delivery_date) as delivery_time, CASE WHEN DATEDIFF(day, order_date, delivery_date) <= 3 THEN 'On Time' ELSE 'Late' END as status FROM orders;",
      businessUseCase: "کتنے دن میں delivery ہوئی۔",
      commonMistakes: "1. Date format غلط ہونا",
      interviewQuestions: "Q1: DATEDIFF کا کیا مقصد ہے؟",
      exercises: "1. DATEDIFF استعمال کریں",
      outputExample: "| order_date | days_ago |\n|---|---|\n| 2024-01-01 | 30 |"
    },
    "DATEADD": {
      explanation: "DATEADD کسی تاریخ میں دن، ماہ، سال وغیرہ شامل کرتا ہے۔",
      syntax: "SELECT DATEADD(day, 7, order_date) FROM table;",
      beginnerExample: "SELECT order_date, DATEADD(day, 7, order_date) as expected_delivery FROM orders;",
      intermediateExample: "SELECT order_date, DATEADD(month, 1, order_date) as next_month FROM orders;",
      advancedExample: "SELECT order_id, order_date, DATEADD(day, 3, order_date) as deadline FROM orders;",
      businessUseCase: "delivery کی تاریخ معلوم کرنا۔",
      commonMistakes: "1. Negative values استعمال کرنا",
      interviewQuestions: "Q1: DATEADD کا کیا مقصد ہے؟",
      exercises: "1. DATEADD استعمال کریں",
      outputExample: "| order_date | expected_delivery |\n|---|---|\n| 2024-01-01 | 2024-01-08 |"
    },
    "GETDATE": {
      explanation: "GETDATE موجودہ تاریخ اور وقت دیتا ہے۔",
      syntax: "SELECT GETDATE();",
      beginnerExample: "SELECT GETDATE() as current_date;",
      intermediateExample: "SELECT order_id, DATEDIFF(day, order_date, GETDATE()) as days_since_order FROM orders;",
      advancedExample: "SELECT order_id, CASE WHEN order_date < DATEADD(month, -3, GETDATE()) THEN 'Old' ELSE 'Recent' END as order_age FROM orders;",
      businessUseCase: "موجودہ تاریخ معلوم کرنا۔",
      commonMistakes: "1. GETDATE() کے بغیر parentheses",
      interviewQuestions: "Q1: GETDATE کا کیا مقصد ہے؟",
      exercises: "1. GETDATE استعمال کریں",
      outputExample: "| current_date |\n|---|\n| 2024-05-23 10:30:45 |"
    },
    "String Functions": {
      explanation: "String functions text کے ساتھ کام کرتے ہیں۔ text کو trim کرنا، replace کرنا، یا substring نکالنا۔",
      syntax: "SELECT TRIM(column), SUBSTRING(column, 1, 5), REPLACE(column, 'old', 'new') FROM table;",
      beginnerExample: "SELECT TRIM(name) FROM customers;",
      intermediateExample: "SELECT SUBSTRING(email, 1, CHARINDEX('@', email)-1) as username FROM customers;",
      advancedExample: "SELECT REPLACE(phone_number, '-', '') as formatted_phone FROM customers;",
      businessUseCase: "ڈیٹا کو صاف کرنا اور format کرنا۔",
      commonMistakes: "1. String functions کا نام غلط ہونا",
      interviewQuestions: "Q1: String functions کیا ہیں؟",
      exercises: "1. مختلف string functions استعمال کریں",
      outputExample: "| TRIM(name) |\n|---|\n| احمد |"
    },
    "TRIM": {
      explanation: "TRIM string کے شروع اور آخر سے خالی جگہیں ہٹاتا ہے۔",
      syntax: "SELECT TRIM(column) FROM table;",
      beginnerExample: "SELECT TRIM(name) FROM customers;",
      intermediateExample: "SELECT TRIM(BOTH ' ' FROM name) FROM customers;",
      advancedExample: "SELECT TRIM(LEADING ' ' FROM address) as cleaned_address FROM customers;",
      businessUseCase: "ڈیٹا میں خالی جگہیں صاف کرنا۔",
      commonMistakes: "1. TRIM کے بغیر parentheses",
      interviewQuestions: "Q1: TRIM کا کیا مقصد ہے؟",
      exercises: "1. TRIM استعمال کریں",
      outputExample: "| TRIM(name) |\n|---|\n| احمد |"
    },
    "SUBSTRING": {
      explanation: "SUBSTRING string کا ایک حصہ نکالتا ہے۔",
      syntax: "SELECT SUBSTRING(column, start, length) FROM table;",
      beginnerExample: "SELECT SUBSTRING(name, 1, 5) FROM customers;",
      intermediateExample: "SELECT SUBSTRING(email, 1, CHARINDEX('@', email)-1) as username FROM customers;",
      advancedExample: "SELECT SUBSTRING(phone_number, 1, 4) as country_code FROM customers;",
      businessUseCase: "email سے username نکالنا۔",
      commonMistakes: "1. Start position 0 سے شروع کرنا",
      interviewQuestions: "Q1: SUBSTRING کا کیا مقصد ہے؟",
      exercises: "1. SUBSTRING استعمال کریں",
      outputExample: "| SUBSTRING(name, 1, 5) |\n|---|\n| احمد |"
    },
    "CONCAT": {
      explanation: "CONCAT متعدد strings کو ملاتا ہے۔",
      syntax: "SELECT CONCAT(column1, ' ', column2) FROM table;",
      beginnerExample: "SELECT CONCAT(first_name, ' ', last_name) as full_name FROM customers;",
      intermediateExample: "SELECT CONCAT(address, ', ', city, ', ', country) as full_address FROM customers;",
      advancedExample: "SELECT CONCAT(SUBSTRING(email, 1, CHARINDEX('@', email)-1), '@company.com') as company_email FROM employees;",
      businessUseCase: "پہلا نام اور آخری نام ملا کر مکمل نام بنانا۔",
      commonMistakes: "1. CONCAT کے بغیر separator",
      interviewQuestions: "Q1: CONCAT کا کیا مقصد ہے؟",
      exercises: "1. CONCAT استعمال کریں",
      outputExample: "| full_name |\n|---|\n| احمد علی |"
    },
    "REPLACE": {
      explanation: "REPLACE string میں کچھ حصہ تبدیل کرتا ہے۔",
      syntax: "SELECT REPLACE(column, 'old_text', 'new_text') FROM table;",
      beginnerExample: "SELECT REPLACE(phone_number, '-', '') as formatted_phone FROM customers;",
      intermediateExample: "SELECT REPLACE(email, '@old.com', '@new.com') as updated_email FROM customers;",
      advancedExample: "SELECT REPLACE(REPLACE(address, 'Street', 'St'), 'Avenue', 'Ave') as shortened_address FROM customers;",
      businessUseCase: "phone numbers کو format کرنا یا email domain تبدیل کرنا۔",
      commonMistakes: "1. REPLACE case-sensitive ہے",
      interviewQuestions: "Q1: REPLACE کا کیا مقصد ہے؟",
      exercises: "1. REPLACE استعمال کریں",
      outputExample: "| formatted_phone |\n|---|\n| 03001234567 |"
    }
  },
  "ADVANCED ANALYTICS": {
    "Subqueries": {
      explanation: "Subquery ایک query کے اندر دوسری query ہے۔ یہ ایک temporary result set بناتا ہے۔",
      syntax: "SELECT * FROM table WHERE column IN (SELECT column FROM table WHERE condition);",
      beginnerExample: "SELECT * FROM employees WHERE department_id IN (SELECT id FROM departments WHERE location = 'Karachi');",
      intermediateExample: "SELECT * FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE total_spent > 50000);",
      advancedExample: "SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);",
      businessUseCase: "وہ employees دیکھنا جن کی تنخواہ اوسط سے زیادہ ہے۔",
      commonMistakes: "1. Subquery میں غلط column 2. Performance issues",
      interviewQuestions: "Q1: Subquery کیا ہے؟",
      exercises: "1. Subqueries استعمال کریں",
      outputExample: "| name | salary |\n|---|---|\n| احمد | 80000 |"
    },
    "Correlated Subqueries": {
      explanation: "Correlated subquery outer query کے rows کو reference کرتا ہے۔ ہر row کے لیے subquery چلتا ہے۔",
      syntax: "SELECT * FROM table1 t1 WHERE column > (SELECT AVG(column) FROM table2 t2 WHERE t1.id = t2.id);",
      beginnerExample: "SELECT * FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id);",
      intermediateExample: "SELECT * FROM orders o WHERE amount > (SELECT AVG(amount) FROM orders WHERE customer_id = o.customer_id);",
      advancedExample: "SELECT * FROM products p WHERE price > (SELECT AVG(price) FROM products WHERE category_id = p.category_id);",
      businessUseCase: "ہر department میں اوسط سے زیادہ تنخواہ والے employees۔",
      commonMistakes: "1. Performance issues 2. Alias غلط ہونا",
      interviewQuestions: "Q1: Correlated subquery کیا ہے؟",
      exercises: "1. Correlated subqueries استعمال کریں",
      outputExample: "| name | salary |\n|---|---|\n| احمد | 80000 |"
    },
    "CTEs": {
      explanation: "CTE (Common Table Expression) ایک temporary named result set ہے۔ WITH keyword سے شروع ہوتا ہے۔",
      syntax: "WITH cte_name AS (SELECT ...) SELECT * FROM cte_name;",
      beginnerExample: "WITH high_earners AS (SELECT * FROM employees WHERE salary > 100000) SELECT * FROM high_earners;",
      intermediateExample: "WITH customer_totals AS (SELECT customer_id, SUM(amount) as total FROM orders GROUP BY customer_id) SELECT * FROM customer_totals WHERE total > 50000;",
      advancedExample: "WITH ranked_employees AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) as rank FROM employees) SELECT * FROM ranked_employees WHERE rank <= 3;",
      businessUseCase: "پیچیدہ queries کو سادہ بنانا۔",
      commonMistakes: "1. CTE کو دوبارہ استعمال کرنا 2. Syntax errors",
      interviewQuestions: "Q1: CTE کیا ہے؟",
      exercises: "1. CTEs استعمال کریں",
      outputExample: "| name | salary |\n|---|---|\n| احمد | 120000 |"
    },
    "Recursive CTEs": {
      explanation: "Recursive CTE خود کو reference کرتا ہے۔ hierarchical data کے لیے استعمال ہوتا ہے۔",
      syntax: "WITH RECURSIVE cte_name AS (SELECT ... UNION ALL SELECT ... FROM cte_name WHERE condition) SELECT * FROM cte_name;",
      beginnerExample: "WITH RECURSIVE numbers AS (SELECT 1 as n UNION ALL SELECT n+1 FROM numbers WHERE n < 10) SELECT * FROM numbers;",
      intermediateExample: "WITH RECURSIVE org_hierarchy AS (SELECT id, name, manager_id, 1 as level FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.name, e.manager_id, oh.level + 1 FROM employees e JOIN org_hierarchy oh ON e.manager_id = oh.id) SELECT * FROM org_hierarchy;",
      advancedExample: "WITH RECURSIVE category_hierarchy AS (SELECT id, name, parent_id, 0 as level FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, c.name, c.parent_id, ch.level + 1 FROM categories c JOIN category_hierarchy ch ON c.parent_id = ch.id) SELECT * FROM category_hierarchy;",
      businessUseCase: "organizational hierarchy دیکھنا۔",
      commonMistakes: "1. Infinite loop 2. Base case غلط ہونا",
      interviewQuestions: "Q1: Recursive CTE کیا ہے؟",
      exercises: "1. Recursive CTEs استعمال کریں",
      outputExample: "| name | level |\n|---|---|\n| CEO | 0 |\n| Manager | 1 |"
    },
    "Window Functions": {
      explanation: "Window functions rows کے ایک group پر کام کرتے ہیں۔ OVER clause استعمال کرتے ہیں۔",
      syntax: "SELECT column, ROW_NUMBER() OVER (PARTITION BY column ORDER BY column) FROM table;",
      beginnerExample: "SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) as rank FROM employees;",
      intermediateExample: "SELECT name, salary, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) as dept_rank FROM employees;",
      advancedExample: "SELECT name, salary, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) as rank, SUM(salary) OVER (PARTITION BY department_id) as dept_total FROM employees;",
      businessUseCase: "ہر department میں top 3 employees دیکھنا۔",
      commonMistakes: "1. PARTITION BY بھول جانا 2. ORDER BY غلط ہونا",
      interviewQuestions: "Q1: Window functions کیا ہیں؟",
      exercises: "1. Window functions استعمال کریں",
      outputExample: "| name | rank |\n|---|---|\n| احمد | 1 |\n| علی | 2 |"
    },
    "ROW_NUMBER": {
      explanation: "ROW_NUMBER ہر row کو unique number دیتا ہے۔ PARTITION BY کے ساتھ groups میں۔",
      syntax: "SELECT column, ROW_NUMBER() OVER (PARTITION BY column ORDER BY column) FROM table;",
      beginnerExample: "SELECT name, ROW_NUMBER() OVER (ORDER BY name) as row_num FROM employees;",
      intermediateExample: "SELECT name, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY name) as dept_row_num FROM employees;",
      advancedExample: "SELECT name, salary, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) as rank FROM employees;",
      businessUseCase: "ہر department میں employees کو rank کرنا۔",
      commonMistakes: "1. Duplicate ranks نہیں ہوتے",
      interviewQuestions: "Q1: ROW_NUMBER کا کیا مقصد ہے؟",
      exercises: "1. ROW_NUMBER استعمال کریں",
      outputExample: "| name | row_num |\n|---|---|\n| احمد | 1 |"
    },
    "RANK": {
      explanation: "RANK rows کو rank دیتا ہے۔ Duplicate values کو same rank دیتا ہے۔",
      syntax: "SELECT column, RANK() OVER (PARTITION BY column ORDER BY column DESC) FROM table;",
      beginnerExample: "SELECT name, salary, RANK() OVER (ORDER BY salary DESC) as rank FROM employees;",
      intermediateExample: "SELECT name, salary, department_id, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) as dept_rank FROM employees;",
      advancedExample: "SELECT name, score, RANK() OVER (ORDER BY score DESC) as rank FROM students;",
      businessUseCase: "students کو ان کے scores کی بنیاد پر rank کرنا۔",
      commonMistakes: "1. RANK اور ROW_NUMBER کو الجھانا",
      interviewQuestions: "Q1: RANK اور ROW_NUMBER میں کیا فرق ہے؟",
      exercises: "1. RANK استعمال کریں",
      outputExample: "| name | rank |\n|---|---|\n| احمد | 1 |\n| علی | 1 |"
    },
    "DENSE_RANK": {
      explanation: "DENSE_RANK rows کو rank دیتا ہے۔ Gaps نہیں ہوتے۔",
      syntax: "SELECT column, DENSE_RANK() OVER (PARTITION BY column ORDER BY column DESC) FROM table;",
      beginnerExample: "SELECT name, salary, DENSE_RANK() OVER (ORDER BY salary DESC) as rank FROM employees;",
      intermediateExample: "SELECT name, score, DENSE_RANK() OVER (ORDER BY score DESC) as rank FROM students;",
      advancedExample: "SELECT name, score, DENSE_RANK() OVER (ORDER BY score DESC) as rank FROM students WHERE score > 50;",
      businessUseCase: "students کو consecutive ranks دینا۔",
      commonMistakes: "1. DENSE_RANK اور RANK کو الجھانا",
      interviewQuestions: "Q1: DENSE_RANK اور RANK میں کیا فرق ہے؟",
      exercises: "1. DENSE_RANK استعمال کریں",
      outputExample: "| name | rank |\n|---|---|\n| احمد | 1 |\n| علی | 2 |"
    },
    "LEAD": {
      explanation: "LEAD اگلی row کی value نکالتا ہے۔",
      syntax: "SELECT column, LEAD(column) OVER (ORDER BY column) FROM table;",
      beginnerExample: "SELECT order_date, amount, LEAD(amount) OVER (ORDER BY order_date) as next_amount FROM orders;",
      intermediateExample: "SELECT month, revenue, LEAD(revenue) OVER (ORDER BY month) as next_month_revenue FROM monthly_sales;",
      advancedExample: "SELECT order_date, amount, LEAD(amount) OVER (ORDER BY order_date) as next_amount, LEAD(amount) OVER (ORDER BY order_date) - amount as difference FROM orders;",
      businessUseCase: "ماہانہ revenue میں تبدیلی دیکھنا۔",
      commonMistakes: "1. LEAD بغیر ORDER BY",
      interviewQuestions: "Q1: LEAD کا کیا مقصد ہے؟",
      exercises: "1. LEAD استعمال کریں",
      outputExample: "| order_date | amount | next_amount |\n|---|---|---|\n| 2024-01-01 | 1000 | 1500 |"
    },
    "LAG": {
      explanation: "LAG پچھلی row کی value نکالتا ہے۔",
      syntax: "SELECT column, LAG(column) OVER (ORDER BY column) FROM table;",
      beginnerExample: "SELECT order_date, amount, LAG(amount) OVER (ORDER BY order_date) as prev_amount FROM orders;",
      intermediateExample: "SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) as prev_month_revenue FROM monthly_sales;",
      advancedExample: "SELECT order_date, amount, LAG(amount) OVER (ORDER BY order_date) as prev_amount, amount - LAG(amount) OVER (ORDER BY order_date) as difference FROM orders;",
      businessUseCase: "ماہانہ revenue میں تبدیلی دیکھنا۔",
      commonMistakes: "1. LAG بغیر ORDER BY",
      interviewQuestions: "Q1: LAG کا کیا مقصد ہے؟",
      exercises: "1. LAG استعمال کریں",
      outputExample: "| order_date | amount | prev_amount |\n|---|---|---|\n| 2024-01-01 | 1000 | NULL |"
    },
    "SUM OVER()": {
      explanation: "SUM OVER() running total بناتا ہے۔ PARTITION BY کے ساتھ groups میں۔",
      syntax: "SELECT column, SUM(column) OVER (ORDER BY column) FROM table;",
      beginnerExample: "SELECT order_date, amount, SUM(amount) OVER (ORDER BY order_date) as running_total FROM orders;",
      intermediateExample: "SELECT customer_id, order_date, amount, SUM(amount) OVER (PARTITION BY customer_id ORDER BY order_date) as customer_total FROM orders;",
      advancedExample: "SELECT month, revenue, SUM(revenue) OVER (ORDER BY month) as cumulative_revenue FROM monthly_sales;",
      businessUseCase: "cumulative sales دیکھنا۔",
      commonMistakes: "1. ORDER BY بھول جانا",
      interviewQuestions: "Q1: SUM OVER() کا کیا مقصد ہے؟",
      exercises: "1. SUM OVER() استعمال کریں",
      outputExample: "| order_date | amount | running_total |\n|---|---|---|\n| 2024-01-01 | 1000 | 1000 |"
    },
    "PARTITION BY": {
      explanation: "PARTITION BY window functions میں groups بناتا ہے۔",
      syntax: "SELECT column, ROW_NUMBER() OVER (PARTITION BY column ORDER BY column) FROM table;",
      beginnerExample: "SELECT name, department_id, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY name) FROM employees;",
      intermediateExample: "SELECT customer_id, order_date, amount, SUM(amount) OVER (PARTITION BY customer_id ORDER BY order_date) as customer_total FROM orders;",
      advancedExample: "SELECT product_id, month, revenue, SUM(revenue) OVER (PARTITION BY product_id ORDER BY month) as product_cumulative FROM monthly_product_sales;",
      businessUseCase: "ہر product کے لیے cumulative sales۔",
      commonMistakes: "1. PARTITION BY بغیر OVER",
      interviewQuestions: "Q1: PARTITION BY کا کیا مقصد ہے؟",
      exercises: "1. PARTITION BY استعمال کریں",
      outputExample: "| product_id | month | revenue | product_cumulative |\n|---|---|---|---|\n| 1 | 2024-01 | 1000 | 1000 |"
    },
    "Running Totals": {
      explanation: "Running total cumulative sum ہے۔ ہر row تک کا مجموعہ۔",
      syntax: "SELECT column, SUM(column) OVER (ORDER BY column ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM table;",
      beginnerExample: "SELECT order_date, amount, SUM(amount) OVER (ORDER BY order_date) as running_total FROM orders;",
      intermediateExample: "SELECT customer_id, order_date, amount, SUM(amount) OVER (PARTITION BY customer_id ORDER BY order_date) as customer_running_total FROM orders;",
      advancedExample: "SELECT month, revenue, SUM(revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as cumulative_revenue FROM monthly_sales;",
      businessUseCase: "cumulative sales track کرنا۔",
      commonMistakes: "1. ROWS clause غلط ہونا",
      interviewQuestions: "Q1: Running total کیا ہے؟",
      exercises: "1. Running totals بنائیں",
      outputExample: "| order_date | amount | running_total |\n|---|---|---|\n| 2024-01-01 | 1000 | 1000 |\n| 2024-01-02 | 500 | 1500 |"
    },
    "Cohort Analysis": {
      explanation: "Cohort analysis ایک group کے users کو ان کے behavior کی بنیاد پر analyze کرتا ہے۔",
      syntax: "SELECT cohort, COUNT(*) as user_count FROM (SELECT user_id, DATE_TRUNC('month', first_purchase_date) as cohort FROM users) GROUP BY cohort;",
      beginnerExample: "SELECT DATE_TRUNC('month', order_date) as cohort, COUNT(DISTINCT customer_id) as customers FROM orders GROUP BY DATE_TRUNC('month', order_date);",
      intermediateExample: "SELECT DATE_TRUNC('month', first_purchase_date) as cohort, COUNT(*) as new_customers, SUM(amount) as total_spent FROM customers GROUP BY DATE_TRUNC('month', first_purchase_date);",
      advancedExample: "SELECT cohort, DATE_TRUNC('month', order_date) as order_month, COUNT(DISTINCT customer_id) as customers FROM (SELECT customer_id, DATE_TRUNC('month', MIN(order_date)) as cohort FROM orders GROUP BY customer_id) c JOIN orders o ON c.customer_id = o.customer_id GROUP BY cohort, DATE_TRUNC('month', order_date);",
      businessUseCase: "ہر ماہ میں نئے کسٹمرز کی retention دیکھنا۔",
      commonMistakes: "1. Cohort definition غلط ہونا",
      interviewQuestions: "Q1: Cohort analysis کیا ہے؟",
      exercises: "1. Cohort analysis کریں",
      outputExample: "| cohort | customers |\n|---|---|\n| 2024-01 | 50 |"
    },
    "RFM Analysis": {
      explanation: "RFM (Recency, Frequency, Monetary) analysis کسٹمرز کو ان کی خریداری کی بنیاد پر segment کرتا ہے۔",
      syntax: "SELECT customer_id, MAX(order_date) as last_purchase, COUNT(*) as purchase_count, SUM(amount) as total_spent FROM orders GROUP BY customer_id;",
      beginnerExample: "SELECT customer_id, MAX(order_date) as recency, COUNT(*) as frequency, SUM(amount) as monetary FROM orders GROUP BY customer_id;",
      intermediateExample: "SELECT customer_id, DATEDIFF(day, MAX(order_date), GETDATE()) as recency_days, COUNT(*) as frequency, SUM(amount) as monetary FROM orders GROUP BY customer_id;",
      advancedExample: "SELECT customer_id, DATEDIFF(day, MAX(order_date), GETDATE()) as recency, COUNT(*) as frequency, SUM(amount) as monetary, CASE WHEN DATEDIFF(day, MAX(order_date), GETDATE()) <= 30 AND COUNT(*) >= 5 AND SUM(amount) > 50000 THEN 'VIP' WHEN DATEDIFF(day, MAX(order_date), GETDATE()) <= 90 THEN 'Active' ELSE 'Inactive' END as segment FROM orders GROUP BY customer_id;",
      businessUseCase: "کسٹمرز کو VIP، Active، اور Inactive میں تقسیم کرنا۔",
      commonMistakes: "1. RFM metrics غلط ہونا",
      interviewQuestions: "Q1: RFM analysis کیا ہے؟",
      exercises: "1. RFM analysis کریں",
      outputExample: "| customer_id | recency | frequency | monetary | segment |\n|---|---|---|---|---|\n| 1 | 5 | 20 | 100000 | VIP |"
    },
    "Retention Analysis": {
      explanation: "Retention analysis یہ دیکھتا ہے کہ کتنے کسٹمرز واپس آتے ہیں۔",
      syntax: "SELECT cohort, month, COUNT(DISTINCT customer_id) as customers FROM cohort_analysis GROUP BY cohort, month;",
      beginnerExample: "SELECT DATE_TRUNC('month', first_purchase_date) as cohort, COUNT(DISTINCT customer_id) as customers FROM customers GROUP BY DATE_TRUNC('month', first_purchase_date);",
      intermediateExample: "SELECT cohort, DATE_TRUNC('month', order_date) as order_month, COUNT(DISTINCT customer_id) as retained_customers FROM (SELECT customer_id, DATE_TRUNC('month', MIN(order_date)) as cohort FROM orders GROUP BY customer_id) c JOIN orders o ON c.customer_id = o.customer_id GROUP BY cohort, DATE_TRUNC('month', order_date);",
      advancedExample: "SELECT cohort, DATEDIFF(month, cohort, order_month) as months_since_first_purchase, COUNT(DISTINCT customer_id) as customers FROM (SELECT customer_id, DATE_TRUNC('month', MIN(order_date)) as cohort FROM orders GROUP BY customer_id) c JOIN (SELECT customer_id, DATE_TRUNC('month', order_date) as order_month FROM orders) o ON c.customer_id = o.customer_id GROUP BY cohort, DATEDIFF(month, cohort, order_month);",
      businessUseCase: "ہر cohort میں retention rate دیکھنا۔",
      commonMistakes: "1. Cohort definition غلط ہونا",
      interviewQuestions: "Q1: Retention analysis کیا ہے؟",
      exercises: "1. Retention analysis کریں",
      outputExample: "| cohort | months_since | customers |\n|---|---|---|\n| 2024-01 | 0 | 100 |\n| 2024-01 | 1 | 80 |"
    }
  },
  "DATA MODELING & OPTIMIZATION": {
    "Fact Tables": {
      explanation: "Fact table میں measurable data ہوتا ہے۔ عام طور پر transactions یا events۔",
      syntax: "CREATE TABLE fact_sales (transaction_id INT, customer_id INT, product_id INT, amount DECIMAL(10,2), date_id INT);",
      beginnerExample: "SELECT * FROM fact_sales;",
      intermediateExample: "SELECT product_id, SUM(amount) as total_sales FROM fact_sales GROUP BY product_id;",
      advancedExample: "SELECT d.date, SUM(f.amount) as daily_sales FROM fact_sales f JOIN dim_date d ON f.date_id = d.date_id GROUP BY d.date;",
      businessUseCase: "تمام transactions کو ایک جگہ store کرنا۔",
      commonMistakes: "1. Fact table میں descriptive data",
      interviewQuestions: "Q1: Fact table کیا ہے؟",
      exercises: "1. Fact table بنائیں",
      outputExample: "Table created"
    },
    "Dimension Tables": {
      explanation: "Dimension table میں descriptive data ہوتا ہے۔ عام طور پر attributes۔",
      syntax: "CREATE TABLE dim_customer (customer_id INT, name VARCHAR(100), city VARCHAR(50));",
      beginnerExample: "SELECT * FROM dim_customer;",
      intermediateExample: "SELECT city, COUNT(*) as customer_count FROM dim_customer GROUP BY city;",
      advancedExample: "SELECT d.city, SUM(f.amount) as total_sales FROM fact_sales f JOIN dim_customer d ON f.customer_id = d.customer_id GROUP BY d.city;",
      businessUseCase: "کسٹمرز کی معلومات store کرنا۔",
      commonMistakes: "1. Dimension table میں transactions",
      interviewQuestions: "Q1: Dimension table کیا ہے؟",
      exercises: "1. Dimension table بنائیں",
      outputExample: "Table created"
    },
    "Star Schema": {
      explanation: "Star schema میں ایک central fact table ہے اور اس کے چاروں طرف dimension tables ہیں۔",
      syntax: "CREATE TABLE fact_sales (...); CREATE TABLE dim_customer (...); CREATE TABLE dim_product (...);",
      beginnerExample: "SELECT * FROM fact_sales f JOIN dim_customer c ON f.customer_id = c.customer_id;",
      intermediateExample: "SELECT d.city, p.category, SUM(f.amount) as sales FROM fact_sales f JOIN dim_customer d ON f.customer_id = d.customer_id JOIN dim_product p ON f.product_id = p.product_id GROUP BY d.city, p.category;",
      advancedExample: "SELECT d.city, p.category, dt.month, SUM(f.amount) as sales FROM fact_sales f JOIN dim_customer d ON f.customer_id = d.customer_id JOIN dim_product p ON f.product_id = p.product_id JOIN dim_date dt ON f.date_id = dt.date_id GROUP BY d.city, p.category, dt.month;",
      businessUseCase: "ڈیٹا warehouse میں data organize کرنا۔",
      commonMistakes: "1. Fact اور dimension کو الجھانا",
      interviewQuestions: "Q1: Star schema کیا ہے؟",
      exercises: "1. Star schema بنائیں",
      outputExample: "Schema created"
    },
    "Snowflake Schema": {
      explanation: "Snowflake schema میں dimension tables کو normalize کیا جاتا ہے۔",
      syntax: "CREATE TABLE dim_customer (...); CREATE TABLE dim_city (...);",
      beginnerExample: "SELECT * FROM fact_sales f JOIN dim_customer c ON f.customer_id = c.customer_id JOIN dim_city ct ON c.city_id = ct.city_id;",
      intermediateExample: "SELECT ct.city_name, SUM(f.amount) as sales FROM fact_sales f JOIN dim_customer c ON f.customer_id = c.customer_id JOIN dim_city ct ON c.city_id = ct.city_id GROUP BY ct.city_name;",
      advancedExample: "SELECT ct.city_name, p.category, SUM(f.amount) as sales FROM fact_sales f JOIN dim_customer c ON f.customer_id = c.customer_id JOIN dim_city ct ON c.city_id = ct.city_id JOIN dim_product p ON f.product_id = p.product_id GROUP BY ct.city_name, p.category;",
      businessUseCase: "ڈیٹا warehouse میں normalized schema۔",
      commonMistakes: "1. بہت زیادہ normalization",
      interviewQuestions: "Q1: Snowflake schema کیا ہے؟",
      exercises: "1. Snowflake schema بنائیں",
      outputExample: "Schema created"
    },
    "Indexing": {
      explanation: "Index queries کو تیز کرتا ہے۔ لیکن insert/update/delete کو سست کرتا ہے۔",
      syntax: "CREATE INDEX idx_customer_id ON orders(customer_id);",
      beginnerExample: "CREATE INDEX idx_email ON customers(email);",
      intermediateExample: "CREATE INDEX idx_order_date ON orders(order_date);",
      advancedExample: "CREATE INDEX idx_composite ON orders(customer_id, order_date);",
      businessUseCase: "بڑے tables میں queries کو تیز کرنا۔",
      commonMistakes: "1. بہت زیادہ indexes 2. غلط columns پر index",
      interviewQuestions: "Q1: Index کیا ہے؟",
      exercises: "1. Index بنائیں",
      outputExample: "Index created"
    },
    "Query Optimization": {
      explanation: "Query optimization queries کو تیز کرنے کے لیے techniques ہیں۔",
      syntax: "SELECT * FROM orders WHERE customer_id IN (...) -- بہتر ہے INNER JOIN سے",
      beginnerExample: "SELECT * FROM orders WHERE customer_id = 1; -- Index استعمال کریں",
      intermediateExample: "SELECT * FROM orders o INNER JOIN customers c ON o.customer_id = c.id; -- بہتر ہے LEFT JOIN سے",
      advancedExample: "SELECT customer_id, SUM(amount) as total FROM orders WHERE order_date > '2024-01-01' GROUP BY customer_id; -- Aggregation پہلے",
      businessUseCase: "سست queries کو تیز کرنا۔",
      commonMistakes: "1. SELECT * استعمال کرنا 2. Subqueries کی جگہ joins",
      interviewQuestions: "Q1: Query optimization کیا ہے؟",
      exercises: "1. Queries optimize کریں",
      outputExample: "Query optimized"
    },
    "Execution Plans": {
      explanation: "Execution plan یہ دکھاتا ہے کہ SQL engine query کو کیسے execute کرتا ہے۔",
      syntax: "EXPLAIN SELECT * FROM orders WHERE customer_id = 1;",
      beginnerExample: "EXPLAIN SELECT * FROM employees;",
      intermediateExample: "EXPLAIN SELECT * FROM orders WHERE order_date > '2024-01-01';",
      advancedExample: "EXPLAIN SELECT * FROM orders o JOIN customers c ON o.customer_id = c.id;",
      businessUseCase: "queries کو analyze کرنا۔",
      commonMistakes: "1. Execution plan کو ignore کرنا",
      interviewQuestions: "Q1: Execution plan کیا ہے؟",
      exercises: "1. Execution plans دیکھیں",
      outputExample: "Execution plan displayed"
    },
    "SQL Performance Tuning": {
      explanation: "Performance tuning queries کو optimize کرنے کی عملی رہنمائی ہے۔",
      syntax: "-- Use indexes, avoid SELECT *, use appropriate joins",
      beginnerExample: "SELECT customer_id, SUM(amount) FROM orders GROUP BY customer_id; -- بہتر ہے SELECT * سے",
      intermediateExample: "SELECT * FROM orders WHERE customer_id IN (1,2,3); -- بہتر ہے OR سے",
      advancedExample: "SELECT * FROM orders WHERE YEAR(order_date) = 2024; -- بہتر ہے BETWEEN سے",
      businessUseCase: "production queries کو optimize کرنا۔",
      commonMistakes: "1. Premature optimization 2. Benchmark نہ کرنا",
      interviewQuestions: "Q1: Performance tuning کیا ہے؟",
      exercises: "1. Queries optimize کریں",
      outputExample: "Performance improved"
    },
    "BigQuery Concepts": {
      explanation: "BigQuery Google کا cloud data warehouse ہے۔ Scalable اور fast queries۔",
      syntax: "SELECT * FROM `project.dataset.table` WHERE date > '2024-01-01';",
      beginnerExample: "SELECT COUNT(*) FROM `my-project.my_dataset.my_table`;",
      intermediateExample: "SELECT DATE(timestamp_column) as date, COUNT(*) FROM `project.dataset.table` GROUP BY DATE(timestamp_column);",
      advancedExample: "SELECT * FROM `project.dataset.table` WHERE _TABLE_SUFFIX BETWEEN '20240101' AND '20240131';",
      businessUseCase: "بڑے ڈیٹا کو analyze کرنا۔",
      commonMistakes: "1. Partition key غلط ہونا",
      interviewQuestions: "Q1: BigQuery کیا ہے؟",
      exercises: "1. BigQuery queries لکھیں",
      outputExample: "Query executed"
    },
    "Snowflake Concepts": {
      explanation: "Snowflake cloud data warehouse ہے۔ Flexible اور scalable۔",
      syntax: "SELECT * FROM database.schema.table WHERE date > '2024-01-01';",
      beginnerExample: "SELECT COUNT(*) FROM my_table;",
      intermediateExample: "SELECT DATE(created_at) as date, COUNT(*) FROM my_table GROUP BY DATE(created_at);",
      advancedExample: "SELECT * FROM my_table WHERE created_at >= CURRENT_DATE - INTERVAL '30 days';",
      businessUseCase: "cloud میں ڈیٹا analyze کرنا۔",
      commonMistakes: "1. Warehouse size غلط ہونا",
      interviewQuestions: "Q1: Snowflake کیا ہے؟",
      exercises: "1. Snowflake queries لکھیں",
      outputExample: "Query executed"
    },
    "Semantic Layer": {
      explanation: "Semantic layer business logic کو define کرتا ہے۔ metrics اور dimensions۔",
      syntax: "-- Define metrics and dimensions in your BI tool",
      beginnerExample: "-- Total Sales metric = SUM(amount)",
      intermediateExample: "-- Customer Segment dimension = CASE WHEN total_spent > 100000 THEN 'VIP' ELSE 'Regular' END",
      advancedExample: "-- Complex metrics with filters and aggregations",
      businessUseCase: "BI tools میں consistent metrics۔",
      commonMistakes: "1. Metrics کی definition غلط ہونا",
      interviewQuestions: "Q1: Semantic layer کیا ہے؟",
      exercises: "1. Semantic layer define کریں",
      outputExample: "Metrics defined"
    },
    "dbt Basics": {
      explanation: "dbt (data build tool) ڈیٹا transformation کو manage کرتا ہے۔",
      syntax: "-- dbt models میں SQL queries",
      beginnerExample: "-- SELECT * FROM raw_data",
      intermediateExample: "-- SELECT customer_id, SUM(amount) as total FROM raw_orders GROUP BY customer_id",
      advancedExample: "-- Complex transformations with dbt macros and tests",
      businessUseCase: "ڈیٹا pipeline کو manage کرنا۔",
      commonMistakes: "1. dbt models میں logic غلط ہونا",
      interviewQuestions: "Q1: dbt کیا ہے؟",
      exercises: "1. dbt models بنائیں",
      outputExample: "Models created"
    },
    "Power BI Semantic Model": {
      explanation: "Power BI میں semantic model relationships اور measures define کرتا ہے۔",
      syntax: "-- Define relationships between tables",
      beginnerExample: "-- One-to-Many relationship between Customers and Orders",
      intermediateExample: "-- Multiple relationships with different cardinalities",
      advancedExample: "-- Complex measures with DAX formulas",
      businessUseCase: "Power BI میں data model بنانا۔",
      commonMistakes: "1. Relationships غلط ہونا",
      interviewQuestions: "Q1: Power BI semantic model کیا ہے؟",
      exercises: "1. Semantic model بنائیں",
      outputExample: "Model created"
    }
  }
};

// Additional content for 2026 SQL TRENDS
const trendTopics = {
  "AI-Assisted SQL": {
    explanation: "AI tools SQL queries لکھنے میں مدد دیتے ہیں۔ ChatGPT، Copilot وغیرہ۔",
    syntax: "-- AI tools natural language سے SQL generate کرتے ہیں",
    beginnerExample: "-- 'Show me all customers from Karachi' -> SELECT * FROM customers WHERE city = 'Karachi'",
    intermediateExample: "-- 'Top 10 products by sales' -> SELECT TOP 10 product_id, SUM(amount) FROM orders GROUP BY product_id ORDER BY SUM(amount) DESC",
    advancedExample: "-- Complex queries with multiple joins and aggregations",
    businessUseCase: "تیزی سے SQL queries لکھنا۔",
    commonMistakes: "1. AI output کو verify نہ کرنا",
    interviewQuestions: "Q1: AI-assisted SQL کیا ہے؟",
    exercises: "1. AI tools استعمال کریں",
    outputExample: "Query generated by AI"
  },
  "Prompt Engineering for SQL": {
    explanation: "Prompt engineering AI کو بہتر نتائج دینے میں مدد دیتا ہے۔",
    syntax: "-- Clear, specific prompts بہتر results دیتے ہیں",
    beginnerExample: "-- 'Show customers' vs 'Show top 10 customers by total purchases in 2024'",
    intermediateExample: "-- Provide context about schema and requirements",
    advancedExample: "-- Include examples of expected output",
    businessUseCase: "AI سے بہتر SQL queries حاصل کرنا۔",
    commonMistakes: "1. Vague prompts",
    interviewQuestions: "Q1: Prompt engineering کیا ہے؟",
    exercises: "1. Prompts لکھیں",
    outputExample: "Better results from AI"
  },
  "SQL Debugging with AI": {
    explanation: "AI SQL errors کو debug کرنے میں مدد دیتا ہے۔",
    syntax: "-- Paste error message اور query AI کو",
    beginnerExample: "-- 'Column not found' error -> AI بتاتا ہے کون سا column غلط ہے",
    intermediateExample: "-- Performance issues کو identify کرنا",
    advancedExample: "-- Complex query logic کو optimize کرنا",
    businessUseCase: "SQL errors کو جلدی fix کرنا۔",
    commonMistakes: "1. Incomplete error information",
    interviewQuestions: "Q1: SQL debugging کیا ہے؟",
    exercises: "1. Errors debug کریں",
    outputExample: "Error fixed"
  },
  "Real-Time Analytics": {
    explanation: "Real-time analytics فوری ڈیٹا insights دیتے ہیں۔",
    syntax: "-- Streaming data سے real-time queries",
    beginnerExample: "-- Live sales dashboard",
    intermediateExample: "-- Real-time customer behavior tracking",
    advancedExample: "-- Complex real-time aggregations",
    businessUseCase: "فوری business decisions لینا۔",
    commonMistakes: "1. Performance issues",
    interviewQuestions: "Q1: Real-time analytics کیا ہے؟",
    exercises: "1. Real-time queries لکھیں",
    outputExample: "Real-time data displayed"
  },
  "Streaming Data": {
    explanation: "Streaming data مسلسل آنے والا ڈیٹا ہے۔ Kafka، Pub/Sub وغیرہ۔",
    syntax: "-- Streaming data کو process کرنا",
    beginnerExample: "-- Event logs سے data نکالنا",
    intermediateExample: "-- Windowed aggregations",
    advancedExample: "-- Complex stream processing",
    businessUseCase: "مسلسل ڈیٹا کو process کرنا۔",
    commonMistakes: "1. State management issues",
    interviewQuestions: "Q1: Streaming data کیا ہے؟",
    exercises: "1. Streaming queries لکھیں",
    outputExample: "Stream processed"
  },
  "Cloud Data Warehouses": {
    explanation: "Cloud data warehouses scalable اور cost-effective ہیں۔ BigQuery، Snowflake، Redshift۔",
    syntax: "-- Cloud warehouses میں queries",
    beginnerExample: "-- SELECT * FROM cloud_table",
    intermediateExample: "-- Complex queries with partitioning",
    advancedExample: "-- Optimized queries for cloud",
    businessUseCase: "بڑے ڈیٹا کو cloud میں store کرنا۔",
    commonMistakes: "1. Cost optimization ignore کرنا",
    interviewQuestions: "Q1: Cloud data warehouses کیا ہیں؟",
    exercises: "1. Cloud queries لکھیں",
    outputExample: "Query executed in cloud"
  },
  "Modern Analytics Stack": {
    explanation: "Modern analytics stack مختلف tools کو ملاتا ہے۔ dbt، Looker، Snowflake وغیرہ۔",
    syntax: "-- Integrated analytics workflow",
    beginnerExample: "-- Data ingestion -> Transformation -> Visualization",
    intermediateExample: "-- Complex data pipelines",
    advancedExample: "-- End-to-end analytics platform",
    businessUseCase: "مکمل analytics solution بنانا۔",
    commonMistakes: "1. Tools کو غلط طریقے سے integrate کرنا",
    interviewQuestions: "Q1: Modern analytics stack کیا ہے؟",
    exercises: "1. Analytics stack بنائیں",
    outputExample: "Stack configured"
  }
};

// Merge all content
Object.assign(topicsContent, { "2026 SQL TRENDS": trendTopics });
